name: Upload to itchi.io
on:
  pull_request:
    branches:
      - main

env:
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Download and install itchi.io butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          rm butler.zip
          chmod +x butler
      - name: Login to itchi.io
        run: ./butler login
      - name: Upload to itchi.io
        run: ./butler push ./dist/index.html karjona/reapers:web --userversion-file ./version.txt
